/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagihanRouteImport } from './routes/tagihan'
import { Route as PenghuniRouteImport } from './routes/penghuni'
import { Route as PengaduanRouteImport } from './routes/pengaduan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KamarRouteImport } from './routes/kamar'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'

const TagihanRoute = TagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => rootRouteImport,
} as any)
const PenghuniRoute = PenghuniRouteImport.update({
  id: '/penghuni',
  path: '/penghuni',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaduanRoute = PengaduanRouteImport.update({
  id: '/pengaduan',
  path: '/pengaduan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KamarRoute = KamarRouteImport.update({
  id: '/kamar',
  path: '/kamar',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kamar': typeof KamarRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/penghuni': typeof PenghuniRoute
  '/tagihan': typeof TagihanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kamar': typeof KamarRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/penghuni': typeof PenghuniRoute
  '/tagihan': typeof TagihanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/kamar': typeof KamarRoute
  '/login': typeof LoginRoute
  '/pengaduan': typeof PengaduanRoute
  '/penghuni': typeof PenghuniRoute
  '/tagihan': typeof TagihanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/kamar'
    | '/login'
    | '/pengaduan'
    | '/penghuni'
    | '/tagihan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/kamar'
    | '/login'
    | '/pengaduan'
    | '/penghuni'
    | '/tagihan'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/kamar'
    | '/login'
    | '/pengaduan'
    | '/penghuni'
    | '/tagihan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  KamarRoute: typeof KamarRoute
  LoginRoute: typeof LoginRoute
  PengaduanRoute: typeof PengaduanRoute
  PenghuniRoute: typeof PenghuniRoute
  TagihanRoute: typeof TagihanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tagihan': {
      id: '/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof TagihanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penghuni': {
      id: '/penghuni'
      path: '/penghuni'
      fullPath: '/penghuni'
      preLoaderRoute: typeof PenghuniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaduan': {
      id: '/pengaduan'
      path: '/pengaduan'
      fullPath: '/pengaduan'
      preLoaderRoute: typeof PengaduanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kamar': {
      id: '/kamar'
      path: '/kamar'
      fullPath: '/kamar'
      preLoaderRoute: typeof KamarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  KamarRoute: KamarRoute,
  LoginRoute: LoginRoute,
  PengaduanRoute: PengaduanRoute,
  PenghuniRoute: PenghuniRoute,
  TagihanRoute: TagihanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
